/**
 * Render the small Markdown subset emitted by structured-renderer.js.
 *
 * This is intentionally not a general Markdown parser. It escapes raw HTML,
 * only creates links for an allow-listed set of schemes, and recognizes the
 * block constructs generated by this plugin.
 */
export function renderMarkdownHTML(markdown) {
    if (typeof markdown !== 'string') {
        throw new TypeError('Markdown must be a string');
    }

    const lines = markdown.replace(/\r\n?/g, '\n').split('\n');
    const output = [];
    let index = 0;

    while (index < lines.length) {
        const line = lines[index];
        if (!line.trim()) {
            index++;
            continue;
        }

        const page = line.match(/^<!--\s*zotero-page:\s*(.*?)\s*-->$/);
        if (page) {
            const value = escapeHTML(page[1]);
            output.push(`<span class="page-marker" data-page="${escapeAttribute(page[1])}">Page ${value}</span>`);
            index++;
            continue;
        }

        const heading = line.match(/^(#{1,6})\s+(.+)$/);
        if (heading) {
            const level = heading[1].length;
            output.push(`<h${level}>${renderInline(heading[2])}</h${level}>`);
            index++;
            continue;
        }

        const codeFence = line.trim().match(/^(`{3,})$/);
        if (codeFence) {
            const body = [];
            index++;
            while (index < lines.length && lines[index].trim() !== codeFence[1]) {
                body.push(lines[index]);
                index++;
            }
            if (index < lines.length) index++;
            output.push(`<pre><code>${escapeHTML(body.join('\n'))}</code></pre>`);
            continue;
        }

        if (line.trim() === '$$') {
            const body = [];
            index++;
            while (index < lines.length && lines[index].trim() !== '$$') {
                body.push(lines[index]);
                index++;
            }
            if (index < lines.length) index++;
            output.push(`<div class="math"><code>${escapeHTML(body.join('\n'))}</code></div>`);
            continue;
        }

        if (isTableStart(lines, index)) {
            const header = splitTableRow(lines[index]);
            index += 2;
            const rows = [];
            while (index < lines.length && isTableRow(lines[index])) {
                rows.push(splitTableRow(lines[index]));
                index++;
            }
            output.push(renderTable(header, rows));
            continue;
        }

        const listMatch = line.match(/^\s*(?:([-+*])|(\d+)\.)\s+(.+)$/);
        if (listMatch) {
            const ordered = Boolean(listMatch[2]);
            const items = [];
            while (index < lines.length) {
                const item = lines[index].match(/^\s*(?:([-+*])|(\d+)\.)\s+(.+)$/);
                if (!item || Boolean(item[2]) !== ordered) break;
                items.push(renderInline(item[3]));
                index++;
            }
            const tag = ordered ? 'ol' : 'ul';
            output.push(`<${tag}>${items.map(item => `<li>${item}</li>`).join('')}</${tag}>`);
            continue;
        }

        if (line.startsWith('> ')) {
            const body = [];
            while (index < lines.length && lines[index].startsWith('> ')) {
                body.push(lines[index].slice(2));
                index++;
            }
            output.push(`<blockquote>${renderInline(body.join('\n')).replace(/\n/g, '<br>')}</blockquote>`);
            continue;
        }

        const paragraph = [line];
        index++;
        while (index < lines.length && lines[index].trim() && !startsBlock(lines, index)) {
            paragraph.push(lines[index]);
            index++;
        }
        output.push(`<p>${renderInline(paragraph.join(' '))}</p>`);
    }

    return output.join('\n');
}

function startsBlock(lines, index) {
    const line = lines[index];
    return /^#{1,6}\s+/.test(line)
        || /^<!--\s*zotero-page:/.test(line)
        || /^`{3,}$/.test(line.trim())
        || line.trim() === '$$'
        || /^\s*(?:[-+*]|\d+\.)\s+/.test(line)
        || line.startsWith('> ')
        || isTableStart(lines, index);
}

function isTableStart(lines, index) {
    return isTableRow(lines[index])
        && index + 1 < lines.length
        && /^\s*\|?(?:\s*:?-{3,}:?\s*\|)+\s*:?-{3,}:?\s*\|?\s*$/.test(lines[index + 1]);
}

function isTableRow(line = '') {
    const trimmed = line.trim();
    return trimmed.startsWith('|') && trimmed.endsWith('|');
}

function splitTableRow(line) {
    return line.trim().slice(1, -1).split(/(?<!\\)\|/).map(cell => cell.trim());
}

function renderTable(header, rows) {
    const head = `<thead><tr>${header.map(cell => `<th>${renderInline(cell)}</th>`).join('')}</tr></thead>`;
    const body = `<tbody>${rows.map(row => `<tr>${row.map(cell => `<td>${renderInline(cell)}</td>`).join('')}</tr>`).join('')}</tbody>`;
    return `<table>${head}${body}</table>`;
}

function renderInline(source) {
    const literals = [];
    const protectedSource = source.replace(/\\([\\#`*_[\]<>])/g, (_match, character) => {
        const token = `\uE000${literals.length}\uE001`;
        literals.push(escapeHTML(character));
        return token;
    });

    const fragments = [];
    let html = escapeHTML(protectedSource);
    html = html.replace(/`([^`]+)`/g, (_match, value) => {
        const token = `\uE002${fragments.length}\uE003`;
        fragments.push(`<code>${value}</code>`);
        return token;
    });
    html = html.replace(
        /\[([^\]]+)]\(((?:https?:\/\/|zotero:\/\/|#)[^)]+)\)/g,
        (_match, label, href) => `<a href="${cleanEscapedAttribute(href)}" rel="noreferrer">${label}</a>`
    );
    html = html.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
    html = html.replace(/\*([^*]+)\*/g, '<em>$1</em>');
    html = html.replace(/&lt;(sup|sub)&gt;(.*?)&lt;\/(sup|sub)&gt;/g, (_match, open, body, close) => {
        return open === close ? `<${open}>${body}</${close}>` : _match;
    });
    html = html.replace(/&lt;br&gt;/g, '<br>');
    html = html.replace(/\uE002(\d+)\uE003/g, (_match, value) => fragments[Number(value)]);
    html = html.replace(/\uE000(\d+)\uE001/g, (_match, value) => literals[Number(value)]);
    return html;
}

function escapeHTML(value) {
    return String(value)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

function escapeAttribute(value) {
    return escapeHTML(value).replace(/\s/g, '');
}

function cleanEscapedAttribute(value) {
    return String(value).replace(/\s/g, '');
}
